FROM coorpacademy/docker-pyspark:2.0.0-alpine
ENV PYSPARK_DRIVER_PYTHON: jupyter-notebook
ENV PYSPARK_DRIVER_PYTHON_OPTS: "--ip=0.0.0.0 --no-browser --allow-root --port=8888"
# GENERAL DEPENDENCIES
RUN apk update && \
    apk add zip

RUN echo "http://dl-8.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk --no-cache --update-cache add gcc gfortran python python-dev py-pip build-base wget freetype-dev libpng-dev openblas-dev
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN pip install numpy scipy pandas matplotlib

# PYTHON DEPENDENCIES
COPY example-requirements.txt /etc/example-requirements.txt
RUN pip install -r /etc/example-requirements.txt && \
    rm /etc/example-requirements.txt

RUN pip install nose ipython==5.0 jupyter
EXPOSE 8888

CMD ["/bin/bash", "./start-spark-jupyter.sh"]